services:
  - type: web
    name: corporate-travel-360
    runtime: docker
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:mem:corporate;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - key: SPRING_DATASOURCE_USERNAME
        value: sa
      - key: SPRING_DATASOURCE_PASSWORD
        value: ""
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.h2.Driver
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: JWT_SECRET
        generateValue: true

