package com.corporate.travel.service;

import com.corporate.travel.entity.Booking;
import com.corporate.travel.entity.ExpenseReport;
import com.corporate.travel.entity.User;
import com.corporate.travel.exception.ResourceNotFoundException;
import com.corporate.travel.repository.BookingRepository;
import com.corporate.travel.repository.ExpenseReportRepository;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;

@Service
public class PdfDocumentService {

    private static final Font TITLE = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
    private static final Font HEADING = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
    private static final Font BODY = FontFactory.getFont(FontFactory.HELVETICA, 10);
    private static final DateTimeFormatter DT = DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm");

    private final BookingRepository bookingRepository;
    private final ExpenseReportRepository expenseReportRepository;

    public PdfDocumentService(BookingRepository bookingRepository, ExpenseReportRepository expenseReportRepository) {
        this.bookingRepository = bookingRepository;
        this.expenseReportRepository = expenseReportRepository;
    }

    @Transactional(readOnly = true)
    public byte[] generateBoardingPassPdf(Long bookingId, Long userId) {
        Booking booking = bookingRepository.findById(bookingId)
                .orElseThrow(() -> new ResourceNotFoundException("Booking", "id", bookingId));
        if (booking.getUser() == null || !booking.getUser().getId().equals(userId)) {
            throw new ResourceNotFoundException("Booking", "id", bookingId);
        }
        User traveler = booking.getUser();
        return buildPdf("Electronic Boarding Pass", doc -> {
            addLine(doc, "PNR: " + safe(booking.getPnrNumber()));
            addLine(doc, "E-Ticket: " + safe(booking.getETicketNumber()));
            addLine(doc, "Booking Ref: " + safe(booking.getBookingReference()));
            addLine(doc, "Passenger: " + safe(traveler.getFullName()));
            addLine(doc, "Route: HYD → DEL | Flight AI-839");
            addLine(doc, "Departure: 07:30 | Gate B14 | Seat 14A");
            addLine(doc, "Total: INR " + booking.getTotalAmount() + " (" + String.valueOf(booking.getPaymentMethod()) + ")");
            addLine(doc, "Status: " + safe(booking.getStatus()));
        });
    }

    @Transactional(readOnly = true)
    public byte[] generateItineraryPdf(Long bookingId, Long userId) {
        Booking booking = bookingRepository.findById(bookingId)
                .orElseThrow(() -> new ResourceNotFoundException("Booking", "id", bookingId));
        if (booking.getUser() == null || !booking.getUser().getId().equals(userId)) {
            throw new ResourceNotFoundException("Booking", "id", bookingId);
        }
        return buildPdf("Corporate Travel Itinerary", doc -> {
            addLine(doc, "Traveler: " + safe(booking.getUser().getFullName()));
            addLine(doc, "PNR: " + safe(booking.getPnrNumber()));
            addLine(doc, "Trip type: " + safe(booking.getBookingType()));
            addLine(doc, "Confirmed amount: INR " + booking.getTotalAmount());
            addLine(doc, "");
            addLine(doc, "Timeline", HEADING);
            addLine(doc, "07:30 — Flight departure (HYD → DEL)");
            addLine(doc, "10:30 — Executive airport transfer");
            addLine(doc, "12:00 — Hotel check-in (corporate rate)");
            addLine(doc, "");
            addLine(doc, "Generated by CorporateTravel360 on " + DT.format(java.time.LocalDateTime.now()));
        });
    }

    @Transactional(readOnly = true)
    public byte[] generateExpenseReportPdf(Long reportId, Long userId) {
        ExpenseReport report = expenseReportRepository.findById(reportId)
                .orElseThrow(() -> new ResourceNotFoundException("ExpenseReport", "id", reportId));
        if (report.getEmployee() == null || !report.getEmployee().getId().equals(userId)) {
            throw new ResourceNotFoundException("ExpenseReport", "id", reportId);
        }
        return buildPdf("Expense Reimbursement Report", doc -> {
            addLine(doc, "Report #: " + safe(report.getReportNumber()));
            addLine(doc, "Employee: " + safe(report.getEmployee().getFullName()));
            addLine(doc, "Title: " + safe(report.getTitle()));
            addLine(doc, "Status: " + safe(report.getStatus()));
            addLine(doc, "Total: INR " + report.getTotalAmount());
            addLine(doc, "");
            PdfPTable table = new PdfPTable(4);
            table.setWidthPercentage(100);
            table.addCell(headerCell("Category"));
            table.addCell(headerCell("Merchant"));
            table.addCell(headerCell("Amount"));
            table.addCell(headerCell("Compliant"));
            report.getItems().forEach(item -> {
                table.addCell(bodyCell(String.valueOf(item.getCategory())));
                table.addCell(bodyCell(safe(item.getMerchantName())));
                table.addCell(bodyCell("INR " + item.getAmount()));
                table.addCell(bodyCell(Boolean.TRUE.equals(item.getPolicyCompliant()) ? "Yes" : "No"));
            });
            doc.add(table);
        });
    }

    private byte[] buildPdf(String title, PdfConsumer consumer) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4, 36, 36, 48, 36);
            PdfWriter.getInstance(doc, out);
            doc.open();
            Paragraph p = new Paragraph(title, TITLE);
            p.setAlignment(Element.ALIGN_CENTER);
            p.setSpacingAfter(16);
            doc.add(p);
            consumer.write(doc);
            doc.close();
            return out.toByteArray();
        } catch (Exception ex) {
            throw new IllegalStateException("Failed to generate PDF: " + ex.getMessage(), ex);
        }
    }

    private PdfPCell headerCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, HEADING));
        cell.setPadding(6);
        return cell;
    }

    private PdfPCell bodyCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, BODY));
        cell.setPadding(5);
        return cell;
    }

    private void addLine(Document doc, String text) throws DocumentException {
        addLine(doc, text, BODY);
    }

    private void addLine(Document doc, String text, Font font) throws DocumentException {
        Paragraph p = new Paragraph(text, font);
        p.setSpacingAfter(6);
        doc.add(p);
    }

    private String safe(Object value) {
        return value == null ? "—" : String.valueOf(value);
    }

    @FunctionalInterface
    private interface PdfConsumer {
        void write(Document doc) throws DocumentException;
    }
}
