package com.corporate.travel.entity.enums;

public enum NotificationType {
    REQUEST_SUBMITTED,
    APPROVAL_REQUIRED,
    REQUEST_APPROVED,
    REQUEST_REJECTED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    FLIGHT_CHANGE,
    EXPENSE_SUBMITTED,
    EXPENSE_APPROVED,
    PAYMENT_COMPLETED,
    EMERGENCY_ALERT,
    POLICY_VIOLATION
}
