package com.corporate.travel.entity.enums;

public enum PermissionType {
    USER_VIEW, USER_CREATE, USER_UPDATE, USER_DELETE,
    COMPANY_VIEW, COMPANY_MANAGE,
    EMPLOYEE_VIEW, EMPLOYEE_MANAGE,
    TRAVEL_REQUEST_CREATE, TRAVEL_REQUEST_VIEW, TRAVEL_REQUEST_UPDATE,
    TRAVEL_REQUEST_SUBMIT, TRAVEL_REQUEST_APPROVE, TRAVEL_REQUEST_REJECT,
    POLICY_VIEW, POLICY_MANAGE,
    BOOKING_VIEW, BOOKING_CREATE, BOOKING_UPDATE, BOOKING_CANCEL,
    EXPENSE_CREATE, EXPENSE_VIEW, EXPENSE_APPROVE,
    REIMBURSEMENT_VIEW, REIMBURSEMENT_PROCESS,
    PAYMENT_VIEW, PAYMENT_PROCESS,
    VENDOR_VIEW, VENDOR_MANAGE,
    REPORT_VIEW, ANALYTICS_VIEW,
    AUDIT_VIEW,
    SYSTEM_ADMIN
}
