package com.corporate.travel.entity.enums;

public enum RequestStatus {
    DRAFT,
    SUBMITTED,
    MANAGER_REVIEW,
    MANAGER_APPROVED,
    HR_BUDGET_REVIEW,
    HR_BUDGET_ALLOCATED,
    TRAVEL_AGENT_ACTION,
    HR_FINAL_REVIEW,
    FINANCE_REVIEW,
    APPROVED,
    REJECTED,
    MODIFICATION_REQUESTED,
    BOOKING_IN_PROGRESS,
    CONFIRMED,
    TRAVEL_ACTIVE,
    COMPLETED,
    EXPENSED,
    CLOSED
}
