package com.corporate.travel.entity.enums;

public enum RoleType {
    ROLE_SUPER_ADMIN,
    ROLE_COMPANY_ADMIN,
    ROLE_TRAVEL_MANAGER,
    ROLE_APPROVER,
    ROLE_EMPLOYEE,
    ROLE_FINANCE,
    ROLE_FINANCE_APPROVER,
    ROLE_DEPARTMENT_HEAD,
    ROLE_AUDITOR,
    ROLE_HR,
    ROLE_VENDOR,
    ROLE_SUPPORT
}
