package com.corporate.travel.controller;

import com.corporate.travel.common.ApiResponse;
import com.corporate.travel.dto.TravelHubDto;
import com.corporate.travel.entity.*;
import com.corporate.travel.entity.enums.RequestStatus;
import com.corporate.travel.repository.*;
import com.corporate.travel.security.AuthenticatedUser;
import com.corporate.travel.security.UserPrincipal;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.web.bind.annotation.*;
import java.math.BigDecimal;
import java.util.List;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/api/travel-hubs")
public class TravelHubController {
    private final TravelRequestRepository requestRepository; private final TravelBudgetRepository budgetRepository; private final TravelDocumentRepository documentRepository; private final TravelAgentContactRepository contactRepository; private final TravelChatMessageRepository chatRepository; private final UserRepository userRepository;
    public TravelHubController(TravelRequestRepository r,TravelBudgetRepository b,TravelDocumentRepository d,TravelAgentContactRepository c,TravelChatMessageRepository ch,UserRepository u){requestRepository=r;budgetRepository=b;documentRepository=d;contactRepository=c;chatRepository=ch;userRepository=u;}
    @GetMapping("/{travelRequestId}") public ResponseEntity<ApiResponse<TravelHubDto.TravelHubResponse>> getHub(@AuthenticationPrincipal UserPrincipal p,@PathVariable("travelRequestId") Long id){return ResponseEntity.ok(ApiResponse.ok(toHub(loadAuthorizedRequest(id,AuthenticatedUser.requireId(p))),"Travel hub retrieved"));}
    @PostMapping("/{travelRequestId}/budget") public ResponseEntity<ApiResponse<TravelHubDto.BudgetResponse>> allocateBudget(@AuthenticationPrincipal UserPrincipal p,@PathVariable("travelRequestId") Long id,@Valid @RequestBody TravelHubDto.BudgetRequest body){Long uid=AuthenticatedUser.requireId(p);requireRole(p,"ROLE_HR","ROLE_COMPANY_ADMIN","ROLE_SUPER_ADMIN");TravelRequest r=requestRepository.findById(id).orElseThrow();TravelBudget b=budgetRepository.findByTravelRequestId(id).orElseGet(TravelBudget::new);b.setTravelRequest(r);b.setAllocatedAmount(body.allocatedAmount());b.setFlightLimit(zero(body.flightLimit()));b.setHotelLimit(zero(body.hotelLimit()));b.setCabLimit(zero(body.cabLimit()));b.setMealLimit(zero(body.mealLimit()));b.setOtherLimit(zero(body.otherLimit()));b.setAllocatedBy(userRepository.findById(uid).orElseThrow());b.setStatus(TravelBudget.BudgetStatus.ALLOCATED);r.setStatus(RequestStatus.HR_BUDGET_ALLOCATED);requestRepository.save(r);return ResponseEntity.ok(ApiResponse.ok(toBudget(budgetRepository.save(b)),"HR budget allocated"));}
    @PostMapping("/{travelRequestId}/agent-contact") public ResponseEntity<ApiResponse<TravelHubDto.AgentContactResponse>> saveAgentContact(@AuthenticationPrincipal UserPrincipal p,@PathVariable("travelRequestId") Long id,@Valid @RequestBody TravelHubDto.AgentContactRequest body){requireRole(p,"ROLE_VENDOR","ROLE_HR","ROLE_COMPANY_ADMIN","ROLE_SUPER_ADMIN","ROLE_SUPPORT");TravelRequest r=requestRepository.findById(id).orElseThrow();TravelAgentContact c=contactRepository.findByTravelRequestId(id).orElseGet(TravelAgentContact::new);c.setTravelRequest(r);c.setAgencyName(body.agencyName());c.setAgentName(body.agentName());c.setPhoneNumber(body.phoneNumber());c.setEmail(body.email());c.setEmergencyPhone(body.emergencyPhone());c.setNotes(body.notes());if(r.getStatus()==RequestStatus.HR_BUDGET_ALLOCATED){r.setStatus(RequestStatus.TRAVEL_AGENT_ACTION);requestRepository.save(r);}return ResponseEntity.ok(ApiResponse.ok(toContact(contactRepository.save(c)),"Travel agent contact saved"));}
    @PostMapping("/{travelRequestId}/final-approve") public ResponseEntity<ApiResponse<String>> finalApprove(@AuthenticationPrincipal UserPrincipal p,@PathVariable("travelRequestId") Long id){requireRole(p,"ROLE_HR","ROLE_COMPANY_ADMIN","ROLE_SUPER_ADMIN");TravelRequest r=requestRepository.findById(id).orElseThrow();TravelBudget b=budgetRepository.findByTravelRequestId(id).orElseThrow(()->new IllegalStateException("HR budget is not allocated"));if(contactRepository.findByTravelRequestId(id).isEmpty())throw new IllegalStateException("Travel agent contact is required before final approval");b.setStatus(TravelBudget.BudgetStatus.HR_APPROVED);budgetRepository.save(b);r.setStatus(RequestStatus.CONFIRMED);requestRepository.save(r);return ResponseEntity.ok(ApiResponse.ok("CONFIRMED","HR final approval completed; travel package confirmed"));}
    @PostMapping("/{travelRequestId}/chat") public ResponseEntity<ApiResponse<TravelHubDto.ChatMessageResponse>> sendChat(@AuthenticationPrincipal UserPrincipal p,@PathVariable("travelRequestId") Long id,@Valid @RequestBody TravelHubDto.ChatRequest body){Long uid=AuthenticatedUser.requireId(p);TravelRequest r=loadAuthorizedRequest(id,uid);TravelChatMessage m=new TravelChatMessage();m.setTravelRequest(r);m.setSender(userRepository.findById(uid).orElseThrow());m.setMessage(body.message());m.setAttachmentName(body.attachmentName());m.setAttachmentKey(body.attachmentKey());return ResponseEntity.ok(ApiResponse.ok(toChat(chatRepository.save(m)),"Message sent"));}
    @GetMapping("/{travelRequestId}/chat") public ResponseEntity<ApiResponse<List<TravelHubDto.ChatMessageResponse>>> chat(@AuthenticationPrincipal UserPrincipal p,@PathVariable("travelRequestId") Long id){TravelRequest r=loadAuthorizedRequest(id,AuthenticatedUser.requireId(p));return ResponseEntity.ok(ApiResponse.ok(chatRepository.findByTravelRequestIdOrderByCreatedAtAsc(r.getId()).stream().map(this::toChat).collect(Collectors.toList()),"Chat retrieved"));}
    private TravelRequest loadAuthorizedRequest(Long id,Long uid){TravelRequest r=requestRepository.findById(id).orElseThrow();boolean owner=r.getEmployee()!=null&&uid.equals(r.getEmployee().getId());boolean privileged=userRepository.findById(uid).map(u->u.getRoles().stream().anyMatch(x->List.of("ROLE_COMPANY_ADMIN","ROLE_SUPER_ADMIN","ROLE_HR","ROLE_FINANCE","ROLE_SUPPORT","ROLE_APPROVER","ROLE_TRAVEL_MANAGER","ROLE_VENDOR").contains(x.getName().name()))).orElse(false);if(!owner&&!privileged)throw new AccessDeniedException("You are not authorized for this travel hub");return r;}
    private void requireRole(UserPrincipal p,String... roles){if(p.getAuthorities().stream().map(GrantedAuthority::getAuthority).noneMatch(a->List.of(roles).contains(a)))throw new AccessDeniedException("Required role is not authorized");}
    private BigDecimal zero(BigDecimal n){return n==null?BigDecimal.ZERO:n;}
    private TravelHubDto.TravelHubResponse toHub(TravelRequest r){var b=budgetRepository.findByTravelRequestId(r.getId()).map(this::toBudget).orElse(null);var a=contactRepository.findByTravelRequestId(r.getId()).map(this::toContact).orElse(null);var d=documentRepository.findByTravelRequestIdOrderByCreatedAtDesc(r.getId()).stream().map(x->new TravelHubDto.DocumentResponse(x.getId(),x.getBooking()==null?null:x.getBooking().getId(),x.getDocumentType(),x.getFileName(),x.getDescription(),"/api/travel-hubs/documents/"+x.getId()+"/download")).collect(Collectors.toList());var c=chatRepository.findByTravelRequestIdOrderByCreatedAtAsc(r.getId()).stream().map(this::toChat).collect(Collectors.toList());return new TravelHubDto.TravelHubResponse(r.getId(),r.getRequestNumber(),r.getTripName(),r.getStatus().name(),b,a,d,c);}
    private TravelHubDto.BudgetResponse toBudget(TravelBudget b){return new TravelHubDto.BudgetResponse(b.getTravelRequest().getId(),b.getAllocatedAmount(),b.getFlightLimit(),b.getHotelLimit(),b.getCabLimit(),b.getMealLimit(),b.getOtherLimit(),b.getStatus());}
    private TravelHubDto.AgentContactResponse toContact(TravelAgentContact c){return new TravelHubDto.AgentContactResponse(c.getTravelRequest().getId(),c.getAgencyName(),c.getAgentName(),c.getPhoneNumber(),c.getEmail(),c.getEmergencyPhone(),c.getNotes());}
    private TravelHubDto.ChatMessageResponse toChat(TravelChatMessage m){return new TravelHubDto.ChatMessageResponse(m.getId(),m.getSender().getId(),m.getSender().getEmail(),m.getSender().getRoles().stream().map(x->x.getName().name()).findFirst().orElse("USER"),m.getMessage(),m.getAttachmentName(),m.getCreatedAt());}
}
